# 베이스 이미지: Python 3.13 slim 버전
FROM python:3.13-slim

# 작업 디렉토리 생성
WORKDIR /app
# Shared Volume용 폴더 생성
RUN mkdir /app/images
# requirements.txt 복사
COPY requirements.txt .
# 필요한 라이브러리 설치
RUN pip install --no-cache-dir -r requirements.txt

# 임시 대기용 무한루프
CMD ["tail", "-f", "/dev/null"]